// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DesktopIndex: typeof import('./src/components/Notes/Desktop/DesktopIndex.vue')['default']
    DesktopLayout: typeof import('./src/components/Layout/Desktop/DesktopLayout.vue')['default']
    DesktopNavigate: typeof import('./src/components/Header/Desktop/DesktopNavigate.vue')['default']
    DetailsCom: typeof import('./src/components/Tasks/Mobile/Details/DetailsCom.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderNavigate: typeof import('./src/components/Header/HeaderNavigate.vue')['default']
    LayoutBuffer: typeof import('./src/components/Layout/Buffer/LayoutBuffer.vue')['default']
    LayoutIndex: typeof import('./src/components/Layout/LayoutIndex.vue')['default']
    ListCom: typeof import('./src/components/Tasks/Mobile/List/ListCom.vue')['default']
    MobileIndex: typeof import('./src/components/Notes/Mobile/MobileIndex.vue')['default']
    MobileLayout: typeof import('./src/components/Layout/Mobile/MobileLayout.vue')['default']
    MobileNavigate: typeof import('./src/components/Header/Mobile/MobileNavigate.vue')['default']
    NoteIcon: typeof import('./src/components/Header/common/svg/NoteIcon.vue')['default']
    OptionCom: typeof import('./src/components/Tasks/Mobile/Option/OptionCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingIcon: typeof import('./src/components/Header/common/svg/SettingIcon.vue')['default']
    SyncIcon: typeof import('./src/components/Header/common/svg/SyncIcon.vue')['default']
    TaskFinishIcon: typeof import('./src/components/Header/common/svg/TaskFinishIcon.vue')['default']
  }
}
