// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DesktopIndex: typeof import('./src/components/Tasks/Desktop/DesktopIndex.vue')['default']
    DesktopNavigate: typeof import('./src/components/Header/Desktop/DesktopNavigate.vue')['default']
    DetailsCom: typeof import('./src/components/Tasks/Desktop/Details/DetailsCom.vue')['default']
    HeaderNavigate: typeof import('./src/components/Header/HeaderNavigate.vue')['default']
    ListCom: typeof import('./src/components/Tasks/Desktop/List/ListCom.vue')['default']
    MobileIndex: typeof import('./src/components/Tasks/Mobile/MobileIndex.vue')['default']
    MobileNavigate: typeof import('./src/components/Header/Mobile/MobileNavigate.vue')['default']
    OptionCom: typeof import('./src/components/Tasks/Desktop/Option/OptionCom.vue')['default']
    OptionsCom: typeof import('./src/components/Tasks/Desktop/Option/OptionsCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
