// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DesktopNavigate: typeof import('./src/components/Header/Desktop/DesktopNavigate.vue')['default']
    HeaderNavigate: typeof import('./src/components/Header/HeaderNavigate.vue')['default']
    MobileNavigate: typeof import('./src/components/Header/Mobile/MobileNavigate.vue')['default']
  }
}
